import torch
import torchvision
import torchvision.transforms as T
from torch.utils.data import DataLoader

from PIL import Image
import numpy as np
import json
import math

from robustness import datasets
from robustness.tools.imagenet_helpers import ImageNetHierarchy, common_superclass_wnid

from utils.datasets.paths import get_imagenet_path

data_dir = "../data"


def big_cats(batch_size, n_workers):
    # Collect WordNet id for 'big cat'
    data_path = get_imagenet_path()
    data_info_path = '../data/IN_info'

    imagenet_hier = ImageNetHierarchy(data_path, data_info_path)

    big_cat_wnid = 'n02127808'
    #big_cat_descendents = imagenet_hier.get_descendants(big_cat_wnid)
    #print('big cat descendents:')
    #for i, desc in enumerate(big_cat_descendents):
    #    print(f'[{i}] wnid: {desc} name: {imagenet_hier.wnid_to_name[desc]}')

    #class_ranges, label_map = imagenet_hier.get_subclasses([big_cat_wnid])
    #print(class_ranges)
    class_ranges = [[288], [289], [290], [291], [292], [293]]

    # Create big cat datset and dataloaders
    big_cat_dataset = datasets.CustomImageNet(data_path, class_ranges)
    train_loader, test_loader = big_cat_dataset.make_loaders(
        workers=n_workers,
        batch_size=batch_size,
        data_aug=False,
        shuffle_train=True,
        shuffle_val=True)
    
    return train_loader, test_loader, class_ranges


def granny_smith(batch_size, n_workers, shuffle=False):
    """
    Returns train and test loader for Granny Smith (subset of ImageNet).

    Arguments:
        batch_size: int - size of batches yielded by the dataloaders
        n_workers: int - number of workers used by the dataloaders
        shuffle: bool - by default, the datapoints are not shuffled
    Returns:
        train_loader: torch.DataLoader - training points and labels
        test_loader: torch.DataLoader - test points and labels
    """
    granny_smith_id = 948
    class_ranges = [[granny_smith_id]]
    data_path = get_imagenet_path()

    # Create big cat datset and dataloaders
    granny_smith_dataset = datasets.CustomImageNet(data_path, class_ranges)
    train_loader, test_loader = granny_smith_dataset.make_loaders(
        workers=n_workers,
        batch_size=batch_size,
        data_aug=False,
        shuffle_train=False,
        shuffle_val=False)
    
    return train_loader, test_loader


def white_shark(batch_size, n_workers, shuffle=False):
    """
    Returns train and test loader for White Shark (subset of ImageNet).

    Arguments:
        batch_size: int - size of batches yielded by the dataloaders
        n_workers: int - number of workers used by the dataloaders
        shuffle: bool - by default, the datapoints are not shuffled
    Returns:
        train_loader: torch.DataLoader - training points and labels
        test_loader: torch.DataLoader - test points and labels
    """
    white_shark_id = 2
    class_ranges = [[white_shark_id]]
    data_path = get_imagenet_path()

    # Create big cat datset and dataloaders
    white_shark_dataset = datasets.CustomImageNet(data_path, class_ranges)
    train_loader, test_loader = white_shark_dataset.make_loaders(
        workers=n_workers,
        batch_size=batch_size,
        data_aug=False,
        shuffle_train=False,
        shuffle_val=False)
    
    return train_loader, test_loader


def tench(batch_size, n_workers, shuffle=False):
    """
    Returns train and test loader for Tench (subset of ImageNet).

    Arguments:
        batch_size: int - size of batches yielded by the dataloaders
        n_workers: int - number of workers used by the dataloaders
        shuffle: bool - by default, the datapoints are not shuffled
    Returns:
        train_loader: torch.DataLoader - training points and labels
        test_loader: torch.DataLoader - test points and labels
    """
    tench_id = 0
    class_ranges = [[tench_id]]
    data_path = get_imagenet_path()

    # Create big cat datset and dataloaders
    tench_dataset = datasets.CustomImageNet(data_path, class_ranges)
    train_loader, test_loader = tench_dataset.make_loaders(
        workers=n_workers,
        batch_size=batch_size,
        data_aug=False,
        shuffle_train=False,
        shuffle_val=False)
    
    return train_loader, test_loader


def imagenet_subset(class_id, batch_size, n_workers, shuffle=False):
    """
    Returns train and test loader for the class corresponding to the given id (subset of ImageNet).

    Arguments:
        class_id: int - one of the imagenet classes
        batch_size: int - size of batches yielded by the dataloaders
        n_workers: int - number of workers used by the dataloaders
        shuffle: bool - by default, the datapoints are not shuffled
    Returns:
        train_loader: torch.DataLoader - training points and labels
        test_loader: torch.DataLoader - test points and labels
    """
    class_ranges = [[class_id]]
    data_path = get_imagenet_path()

    # Create big cat datset and dataloaders
    dataset = datasets.CustomImageNet(data_path, class_ranges)

    train_loader, test_loader = dataset.make_loaders(
        workers=n_workers,
        batch_size=batch_size,
        data_aug=False,
        shuffle_train=False,
        shuffle_val=False)
    
    return train_loader, test_loader


def celeba_attribute(attribute, train=True, valid=True, test=True):
    """
    Loads training, validation, and test set of the CelebA dataset 
    with the given attribute as target.

    Args:
        attribute: int - Index of the attribute that will be used as target.
        train: bool - If True, training data will be returned.
        valid: bool - If True, validation data will be returned.
        test: bool - If True, testing data will be returned.

    Returns:
        data: dict - Keys are in ["train", "valid", "test"] containing the (Pytorch) dataset 
    """
    def transform_target(target):
        if len(target.shape) == 1:
            return target[attribute]
        return target[:, attribute]
    
    data = {}

    if train:
        data["train"] = torchvision.datasets.CelebA(
            root=data_dir,
            split="train",
            download=False,
            transform=torchvision.transforms.ToTensor(),
            target_transform=transform_target
        )

    if valid:   
        data["valid"] = torchvision.datasets.CelebA(
            root=data_dir,
            split="valid",
            download=False,
            transform=torchvision.transforms.ToTensor(),
            target_transform=transform_target
        )

    if test:
        data["test"] = torchvision.datasets.CelebA(
            root=data_dir,
            split="test",
            download=False,
            transform=torchvision.transforms.ToTensor(),
            target_transform=transform_target
        )

    return data

def celeba_blond():
    """
    Loads train, valid and test set for the CelebA dataset 
    with target Male (spurious feature Blond_hair).

    Returns:
        data: dict - Keys are in ["train", "valid", "test"] containing the (Pytorch) dataset
    """
    return celeba_attribute(20)


def celeba_grey():
    """
    Loads train, valid and test set for the CelebA dataset 
    with target Grey_hair.
    
    Returns:
        data: dict - Keys are in ["train", "valid", "test"] containing the (Pytorch) dataset
    """
    return celeba_attribute(17)


class SquareMNIST(torch.utils.data.Dataset):
    def __init__(self, size, n_spurious, spurious_feature):
        indices_0_1 = json.load(open("../data/mnist/mnist_0_1_image_ids.json"))
        self.data = torchvision.datasets.MNIST(
            root=data_dir,
            download=True,
            transform=torchvision.transforms.ToTensor()
        )
        self.data = torch.utils.data.Subset(self.data, indices_0_1)
        assert size <= 28
        self.square_size = size
        assert n_spurious <= 6000
        self.n_spurious = n_spurious
        assert spurious_feature in [0,1]
        self.spurious_feature = spurious_feature

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img, lab = self.data[idx]
        if self.spurious_feature == 0 and idx < self.n_spurious:
            return self._add_square(img, self.square_size), lab
        if self.spurious_feature == 1 and idx >= 6000 and idx < self.n_spurious + 6000:
            return self._add_square(img, self.square_size), lab
        return img, lab

    def _add_square(self, img, size):
        square = torch.zeros((28,28))
        square[:size, :size] = 1
        return img + square


def square_mnist(size, n_spurious, spurious_feature, split=True):
    """
    Loads MNIST data for the classes 0 and 1. A small square (spurious feature) is added to
    some of the training images belonging to one of the classes.

    Args:
        size: int - Length of the square in pixel.
        n_spurious: int - Number of training images where the spurious feature is added
        spurious_feature: 0 or 1: The spurious features are added to images of this class.
        split: bool - If True, the data will be split 80/10/10 (train/valid/test).

    Returns:
        data: dict - Keys are in ["train", "valid", "test"] containing the (Pytorch) dataset 
    """    
    dataset = SquareMNIST(size, n_spurious, spurious_feature)
    
    data = {}
    n_zeros = 6000
    perm_0 = torch.randperm(n_zeros)
    perm_1 = torch.randperm(n_zeros) + n_zeros

    if split:
        idx_train = torch.cat((perm_0[:int(0.8*n_zeros)],perm_1[:int(0.8*n_zeros)]))
        idx_valid = torch.cat((perm_0[int(0.8*n_zeros):int(0.9*n_zeros)],perm_1[int(0.8*n_zeros):int(0.9*n_zeros)]))
        idx_test = torch.cat((perm_0[int(0.9*n_zeros):],perm_0[int(0.9*n_zeros):]))
        
        data["train"] = torch.utils.data.Subset(dataset, idx_train)
        data["valid"] = torch.utils.data.Subset(dataset, idx_valid)
        data["test"] = torch.utils.data.Subset(dataset, idx_test)

        return data

    data["train"] = torch.utils.data.Subset(dataset, perm_0+perm_1)

    return data


class ColorMNIST(torch.utils.data.Dataset):
    def __init__(self, frac_spurious):
        indices_0_1 = json.load(open("../data/mnist/mnist_0_1_image_ids.json"))
        self.data = torchvision.datasets.MNIST(
            root=data_dir,
            download=True,
            transform=torchvision.transforms.ToTensor()
        )
        self.data = torch.utils.data.Subset(self.data, indices_0_1)
        assert frac_spurious >= 0 and frac_spurious <= 1
        self.frac_spurious = frac_spurious
        
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img, lab = self.data[idx]
        idx_0 = 0
        
        idx_0_red = idx_0 + self.frac_spurious/2 * 6000
        if idx < math.floor(idx_0_red):
            return self._rgb_img(img, "red"), lab
        
        idx_0_purple = idx_0_red + self.frac_spurious/2 * 6000
        if idx < math.floor(idx_0_purple):
            return self._rgb_img(img, "purple"), lab
        
        idx_0_green = idx_0_purple + (1-self.frac_spurious)/2 * 6000
        if idx < math.floor(idx_0_green):
            return self._rgb_img(img, "green"), lab

        idx_0_pink = idx_0_green + (1-self.frac_spurious)/2 * 6000
        if idx < math.floor(idx_0_pink):
             return self._rgb_img(img, "pink"), lab

        idx_1_red = idx_0_pink + (1-self.frac_spurious)/2 * 6000
        if idx < math.floor(idx_1_red):
            return self._rgb_img(img, "red"), lab        
        
        idx_1_purple = idx_1_red + (1-self.frac_spurious)/2 * 6000
        if idx < math.floor(idx_1_purple):
            return self._rgb_img(img, "purple"), lab

        idx_1_green = idx_1_purple + self.frac_spurious/2 * 6000
        if idx < math.floor(idx_1_green):
            return self._rgb_img(img, "green"), lab
        else:
            return self._rgb_img(img, "pink"), lab

    def _rgb_img(self, img, color):
        rgb_img = torch.ones((28,28,3))

        if color == "red":
            rgb_img = torch.ones((28,28,3)) *  torch.tensor([1, 0, 0])
        if color == "green":
            rgb_img = torch.ones((28,28,3)) * torch.tensor([0, 1, 0])
        if color == "pink":
            rgb_img = torch.ones((28,28,3)) * torch.tensor([1,0.5,1])
        if color == "purple":
            rgb_img = torch.ones((28,28,3)) * torch.tensor([0.5,0,1])
        
        if len(img.shape)>2:
            rgb_img[img[0] > 0] = 255
        else: 
            rgb_img[img > 0] = 255
        return rgb_img


def color_mnist(frac_spurious, split=True):
    """
    Loads MNIST RGB data for the classes 0 and 1. The backgrounds are colored in red, purple, pink, or green.
    Most of the images with class zero have red or purple background, most of the images with class one have
    pink or green background.

    Args:
        frac_spurious: float - Fraction of the images that have the spuriously colored background.
        split: bool - If True, the data will be split 80/10/10 (train/valid/test).

    Returns:
        data: dict - Keys are in ["train", "valid", "test"] containing the (Pytorch) dataset 
    """    
    dataset = ColorMNIST(frac_spurious)
    
    data = {}
    n_zeros = 6000
    perm_0 = torch.randperm(n_zeros)
    perm_1 = torch.randperm(n_zeros) + n_zeros

    if split:
        idx_train = torch.cat((perm_0[:int(0.8*n_zeros)],perm_1[:int(0.8*n_zeros)]))
        idx_valid = torch.cat((perm_0[int(0.8*n_zeros):int(0.9*n_zeros)],perm_1[int(0.8*n_zeros):int(0.9*n_zeros)]))
        idx_test = torch.cat((perm_0[int(0.9*n_zeros):],perm_0[int(0.9*n_zeros):]))
        
        data["train"] = torch.utils.data.Subset(dataset, idx_train)
        data["valid"] = torch.utils.data.Subset(dataset, idx_valid)
        data["test"] = torch.utils.data.Subset(dataset, idx_test)

        return data

    data["train"] = torch.utils.data.Subset(dataset, perm_0+perm_1)

    return data


def imagenet_resize(image):
    """
    Resizes image to imagenet resolution.
    Arguments:
        image - ndarray, input image
    Returns:
        224x224 PIL image, resized version 
    """    
    return T.CenterCrop(T.Resize(256)(Image.fromarray(image)))


imagenet_label2class_long = {0: 'tench, Tinca tinca',
 1: 'goldfish, Carassius auratus',
 2: 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
 3: 'tiger shark, Galeocerdo cuvieri',
 4: 'hammerhead, hammerhead shark',
 5: 'electric ray, crampfish, numbfish, torpedo',
 6: 'stingray',
 7: 'cock',
 8: 'hen',
 9: 'ostrich, Struthio camelus',
 10: 'brambling, Fringilla montifringilla',
 11: 'goldfinch, Carduelis carduelis',
 12: 'house finch, linnet, Carpodacus mexicanus',
 13: 'junco, snowbird',
 14: 'indigo bunting, indigo finch, indigo bird, Passerina cyanea',
 15: 'robin, American robin, Turdus migratorius',
 16: 'bulbul',
 17: 'jay',
 18: 'magpie',
 19: 'chickadee',
 20: 'water ouzel, dipper',
 21: 'kite',
 22: 'bald eagle, American eagle, Haliaeetus leucocephalus',
 23: 'vulture',
 24: 'great grey owl, great gray owl, Strix nebulosa',
 25: 'European fire salamander, Salamandra salamandra',
 26: 'common newt, Triturus vulgaris',
 27: 'eft',
 28: 'spotted salamander, Ambystoma maculatum',
 29: 'axolotl, mud puppy, Ambystoma mexicanum',
 30: 'bullfrog, Rana catesbeiana',
 31: 'tree frog, tree-frog',
 32: 'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui',
 33: 'loggerhead, loggerhead turtle, Caretta caretta',
 34: 'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea',
 35: 'mud turtle',
 36: 'terrapin',
 37: 'box turtle, box tortoise',
 38: 'banded gecko',
 39: 'common iguana, iguana, Iguana iguana',
 40: 'American chameleon, anole, Anolis carolinensis',
 41: 'whiptail, whiptail lizard',
 42: 'agama',
 43: 'frilled lizard, Chlamydosaurus kingi',
 44: 'alligator lizard',
 45: 'Gila monster, Heloderma suspectum',
 46: 'green lizard, Lacerta viridis',
 47: 'African chameleon, Chamaeleo chamaeleon',
 48: 'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis',
 49: 'African crocodile, Nile crocodile, Crocodylus niloticus',
 50: 'American alligator, Alligator mississipiensis',
 51: 'triceratops',
 52: 'thunder snake, worm snake, Carphophis amoenus',
 53: 'ringneck snake, ring-necked snake, ring snake',
 54: 'hognose snake, puff adder, sand viper',
 55: 'green snake, grass snake',
 56: 'king snake, kingsnake',
 57: 'garter snake, grass snake',
 58: 'water snake',
 59: 'vine snake',
 60: 'night snake, Hypsiglena torquata',
 61: 'boa constrictor, Constrictor constrictor',
 62: 'rock python, rock snake, Python sebae',
 63: 'Indian cobra, Naja naja',
 64: 'green mamba',
 65: 'sea snake',
 66: 'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus',
 67: 'diamondback, diamondback rattlesnake, Crotalus adamanteus',
 68: 'sidewinder, horned rattlesnake, Crotalus cerastes',
 69: 'trilobite',
 70: 'harvestman, daddy longlegs, Phalangium opilio',
 71: 'scorpion',
 72: 'black and gold garden spider, Argiope aurantia',
 73: 'barn spider, Araneus cavaticus',
 74: 'garden spider, Aranea diademata',
 75: 'black widow, Latrodectus mactans',
 76: 'tarantula',
 77: 'wolf spider, hunting spider',
 78: 'tick',
 79: 'centipede',
 80: 'black grouse',
 81: 'ptarmigan',
 82: 'ruffed grouse, partridge, Bonasa umbellus',
 83: 'prairie chicken, prairie grouse, prairie fowl',
 84: 'peacock',
 85: 'quail',
 86: 'partridge',
 87: 'African grey, African gray, Psittacus erithacus',
 88: 'macaw',
 89: 'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita',
 90: 'lorikeet',
 91: 'coucal',
 92: 'bee eater',
 93: 'hornbill',
 94: 'hummingbird',
 95: 'jacamar',
 96: 'toucan',
 97: 'drake',
 98: 'red-breasted merganser, Mergus serrator',
 99: 'goose',
 100: 'black swan, Cygnus atratus',
 101: 'tusker',
 102: 'echidna, spiny anteater, anteater',
 103: 'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus',
 104: 'wallaby, brush kangaroo',
 105: 'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus',
 106: 'wombat',
 107: 'jellyfish',
 108: 'sea anemone, anemone',
 109: 'brain coral',
 110: 'flatworm, platyhelminth',
 111: 'nematode, nematode worm, roundworm',
 112: 'conch',
 113: 'snail',
 114: 'slug',
 115: 'sea slug, nudibranch',
 116: 'chiton, coat-of-mail shell, sea cradle, polyplacophore',
 117: 'chambered nautilus, pearly nautilus, nautilus',
 118: 'Dungeness crab, Cancer magister',
 119: 'rock crab, Cancer irroratus',
 120: 'fiddler crab',
 121: 'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica',
 122: 'American lobster, Northern lobster, Maine lobster, Homarus americanus',
 123: 'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish',
 124: 'crayfish, crawfish, crawdad, crawdaddy',
 125: 'hermit crab',
 126: 'isopod',
 127: 'white stork, Ciconia ciconia',
 128: 'black stork, Ciconia nigra',
 129: 'spoonbill',
 130: 'flamingo',
 131: 'little blue heron, Egretta caerulea',
 132: 'American egret, great white heron, Egretta albus',
 133: 'bittern',
 134: 'crane',
 135: 'limpkin, Aramus pictus',
 136: 'European gallinule, Porphyrio porphyrio',
 137: 'American coot, marsh hen, mud hen, water hen, Fulica americana',
 138: 'bustard',
 139: 'ruddy turnstone, Arenaria interpres',
 140: 'red-backed sandpiper, dunlin, Erolia alpina',
 141: 'redshank, Tringa totanus',
 142: 'dowitcher',
 143: 'oystercatcher, oyster catcher',
 144: 'pelican',
 145: 'king penguin, Aptenodytes patagonica',
 146: 'albatross, mollymawk',
 147: 'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus',
 148: 'killer whale, killer, orca, grampus, sea wolf, Orcinus orca',
 149: 'dugong, Dugong dugon',
 150: 'sea lion',
 151: 'Chihuahua',
 152: 'Japanese spaniel',
 153: 'Maltese dog, Maltese terrier, Maltese',
 154: 'Pekinese, Pekingese, Peke',
 155: 'Shih-Tzu',
 156: 'Blenheim spaniel',
 157: 'papillon',
 158: 'toy terrier',
 159: 'Rhodesian ridgeback',
 160: 'Afghan hound, Afghan',
 161: 'basset, basset hound',
 162: 'beagle',
 163: 'bloodhound, sleuthhound',
 164: 'bluetick',
 165: 'black-and-tan coonhound',
 166: 'Walker hound, Walker foxhound',
 167: 'English foxhound',
 168: 'redbone',
 169: 'borzoi, Russian wolfhound',
 170: 'Irish wolfhound',
 171: 'Italian greyhound',
 172: 'whippet',
 173: 'Ibizan hound, Ibizan Podenco',
 174: 'Norwegian elkhound, elkhound',
 175: 'otterhound, otter hound',
 176: 'Saluki, gazelle hound',
 177: 'Scottish deerhound, deerhound',
 178: 'Weimaraner',
 179: 'Staffordshire bullterrier, Staffordshire bull terrier',
 180: 'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier',
 181: 'Bedlington terrier',
 182: 'Border terrier',
 183: 'Kerry blue terrier',
 184: 'Irish terrier',
 185: 'Norfolk terrier',
 186: 'Norwich terrier',
 187: 'Yorkshire terrier',
 188: 'wire-haired fox terrier',
 189: 'Lakeland terrier',
 190: 'Sealyham terrier, Sealyham',
 191: 'Airedale, Airedale terrier',
 192: 'cairn, cairn terrier',
 193: 'Australian terrier',
 194: 'Dandie Dinmont, Dandie Dinmont terrier',
 195: 'Boston bull, Boston terrier',
 196: 'miniature schnauzer',
 197: 'giant schnauzer',
 198: 'standard schnauzer',
 199: 'Scotch terrier, Scottish terrier, Scottie',
 200: 'Tibetan terrier, chrysanthemum dog',
 201: 'silky terrier, Sydney silky',
 202: 'soft-coated wheaten terrier',
 203: 'West Highland white terrier',
 204: 'Lhasa, Lhasa apso',
 205: 'flat-coated retriever',
 206: 'curly-coated retriever',
 207: 'golden retriever',
 208: 'Labrador retriever',
 209: 'Chesapeake Bay retriever',
 210: 'German short-haired pointer',
 211: 'vizsla, Hungarian pointer',
 212: 'English setter',
 213: 'Irish setter, red setter',
 214: 'Gordon setter',
 215: 'Brittany spaniel',
 216: 'clumber, clumber spaniel',
 217: 'English springer, English springer spaniel',
 218: 'Welsh springer spaniel',
 219: 'cocker spaniel, English cocker spaniel, cocker',
 220: 'Sussex spaniel',
 221: 'Irish water spaniel',
 222: 'kuvasz',
 223: 'schipperke',
 224: 'groenendael',
 225: 'malinois',
 226: 'briard',
 227: 'kelpie',
 228: 'komondor',
 229: 'Old English sheepdog, bobtail',
 230: 'Shetland sheepdog, Shetland sheep dog, Shetland',
 231: 'collie',
 232: 'Border collie',
 233: 'Bouvier des Flandres, Bouviers des Flandres',
 234: 'Rottweiler',
 235: 'German shepherd, German shepherd dog, German police dog, alsatian',
 236: 'Doberman, Doberman pinscher',
 237: 'miniature pinscher',
 238: 'Greater Swiss Mountain dog',
 239: 'Bernese mountain dog',
 240: 'Appenzeller',
 241: 'EntleBucher',
 242: 'boxer',
 243: 'bull mastiff',
 244: 'Tibetan mastiff',
 245: 'French bulldog',
 246: 'Great Dane',
 247: 'Saint Bernard, St Bernard',
 248: 'Eskimo dog, husky',
 249: 'malamute, malemute, Alaskan malamute',
 250: 'Siberian husky',
 251: 'dalmatian, coach dog, carriage dog',
 252: 'affenpinscher, monkey pinscher, monkey dog',
 253: 'basenji',
 254: 'pug, pug-dog',
 255: 'Leonberg',
 256: 'Newfoundland, Newfoundland dog',
 257: 'Great Pyrenees',
 258: 'Samoyed, Samoyede',
 259: 'Pomeranian',
 260: 'chow, chow chow',
 261: 'keeshond',
 262: 'Brabancon griffon',
 263: 'Pembroke, Pembroke Welsh corgi',
 264: 'Cardigan, Cardigan Welsh corgi',
 265: 'toy poodle',
 266: 'miniature poodle',
 267: 'standard poodle',
 268: 'Mexican hairless',
 269: 'timber wolf, grey wolf, gray wolf, Canis lupus',
 270: 'white wolf, Arctic wolf, Canis lupus tundrarum',
 271: 'red wolf, maned wolf, Canis rufus, Canis niger',
 272: 'coyote, prairie wolf, brush wolf, Canis latrans',
 273: 'dingo, warrigal, warragal, Canis dingo',
 274: 'dhole, Cuon alpinus',
 275: 'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus',
 276: 'hyena, hyaena',
 277: 'red fox, Vulpes vulpes',
 278: 'kit fox, Vulpes macrotis',
 279: 'Arctic fox, white fox, Alopex lagopus',
 280: 'grey fox, gray fox, Urocyon cinereoargenteus',
 281: 'tabby, tabby cat',
 282: 'tiger cat',
 283: 'Persian cat',
 284: 'Siamese cat, Siamese',
 285: 'Egyptian cat',
 286: 'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor',
 287: 'lynx, catamount',
 288: 'leopard, Panthera pardus',
 289: 'snow leopard, ounce, Panthera uncia',
 290: 'jaguar, panther, Panthera onca, Felis onca',
 291: 'lion, king of beasts, Panthera leo',
 292: 'tiger, Panthera tigris',
 293: 'cheetah, chetah, Acinonyx jubatus',
 294: 'brown bear, bruin, Ursus arctos',
 295: 'American black bear, black bear, Ursus americanus, Euarctos americanus',
 296: 'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus',
 297: 'sloth bear, Melursus ursinus, Ursus ursinus',
 298: 'mongoose',
 299: 'meerkat, mierkat',
 300: 'tiger beetle',
 301: 'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle',
 302: 'ground beetle, carabid beetle',
 303: 'long-horned beetle, longicorn, longicorn beetle',
 304: 'leaf beetle, chrysomelid',
 305: 'dung beetle',
 306: 'rhinoceros beetle',
 307: 'weevil',
 308: 'fly',
 309: 'bee',
 310: 'ant, emmet, pismire',
 311: 'grasshopper, hopper',
 312: 'cricket',
 313: 'walking stick, walkingstick, stick insect',
 314: 'cockroach, roach',
 315: 'mantis, mantid',
 316: 'cicada, cicala',
 317: 'leafhopper',
 318: 'lacewing, lacewing fly',
 319: "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk",
 320: 'damselfly',
 321: 'admiral',
 322: 'ringlet, ringlet butterfly',
 323: 'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus',
 324: 'cabbage butterfly',
 325: 'sulphur butterfly, sulfur butterfly',
 326: 'lycaenid, lycaenid butterfly',
 327: 'starfish, sea star',
 328: 'sea urchin',
 329: 'sea cucumber, holothurian',
 330: 'wood rabbit, cottontail, cottontail rabbit',
 331: 'hare',
 332: 'Angora, Angora rabbit',
 333: 'hamster',
 334: 'porcupine, hedgehog',
 335: 'fox squirrel, eastern fox squirrel, Sciurus niger',
 336: 'marmot',
 337: 'beaver',
 338: 'guinea pig, Cavia cobaya',
 339: 'sorrel',
 340: 'zebra',
 341: 'hog, pig, grunter, squealer, Sus scrofa',
 342: 'wild boar, boar, Sus scrofa',
 343: 'warthog',
 344: 'hippopotamus, hippo, river horse, Hippopotamus amphibius',
 345: 'ox',
 346: 'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis',
 347: 'bison',
 348: 'ram, tup',
 349: 'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis',
 350: 'ibex, Capra ibex',
 351: 'hartebeest',
 352: 'impala, Aepyceros melampus',
 353: 'gazelle',
 354: 'Arabian camel, dromedary, Camelus dromedarius',
 355: 'llama',
 356: 'weasel',
 357: 'mink',
 358: 'polecat, fitch, foulmart, foumart, Mustela putorius',
 359: 'black-footed ferret, ferret, Mustela nigripes',
 360: 'otter',
 361: 'skunk, polecat, wood pussy',
 362: 'badger',
 363: 'armadillo',
 364: 'three-toed sloth, ai, Bradypus tridactylus',
 365: 'orangutan, orang, orangutang, Pongo pygmaeus',
 366: 'gorilla, Gorilla gorilla',
 367: 'chimpanzee, chimp, Pan troglodytes',
 368: 'gibbon, Hylobates lar',
 369: 'siamang, Hylobates syndactylus, Symphalangus syndactylus',
 370: 'guenon, guenon monkey',
 371: 'patas, hussar monkey, Erythrocebus patas',
 372: 'baboon',
 373: 'macaque',
 374: 'langur',
 375: 'colobus, colobus monkey',
 376: 'proboscis monkey, Nasalis larvatus',
 377: 'marmoset',
 378: 'capuchin, ringtail, Cebus capucinus',
 379: 'howler monkey, howler',
 380: 'titi, titi monkey',
 381: 'spider monkey, Ateles geoffroyi',
 382: 'squirrel monkey, Saimiri sciureus',
 383: 'Madagascar cat, ring-tailed lemur, Lemur catta',
 384: 'indri, indris, Indri indri, Indri brevicaudatus',
 385: 'Indian elephant, Elephas maximus',
 386: 'African elephant, Loxodonta africana',
 387: 'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens',
 388: 'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca',
 389: 'barracouta, snoek',
 390: 'eel',
 391: 'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch',
 392: 'rock beauty, Holocanthus tricolor',
 393: 'anemone fish',
 394: 'sturgeon',
 395: 'gar, garfish, garpike, billfish, Lepisosteus osseus',
 396: 'lionfish',
 397: 'puffer, pufferfish, blowfish, globefish',
 398: 'abacus',
 399: 'abaya',
 400: "academic gown, academic robe, judge's robe",
 401: 'accordion, piano accordion, squeeze box',
 402: 'acoustic guitar',
 403: 'aircraft carrier, carrier, flattop, attack aircraft carrier',
 404: 'airliner',
 405: 'airship, dirigible',
 406: 'altar',
 407: 'ambulance',
 408: 'amphibian, amphibious vehicle',
 409: 'analog clock',
 410: 'apiary, bee house',
 411: 'apron',
 412: 'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin',
 413: 'assault rifle, assault gun',
 414: 'backpack, back pack, knapsack, packsack, rucksack, haversack',
 415: 'bakery, bakeshop, bakehouse',
 416: 'balance beam, beam',
 417: 'balloon',
 418: 'ballpoint, ballpoint pen, ballpen, Biro',
 419: 'Band Aid',
 420: 'banjo',
 421: 'bannister, banister, balustrade, balusters, handrail',
 422: 'barbell',
 423: 'barber chair',
 424: 'barbershop',
 425: 'barn',
 426: 'barometer',
 427: 'barrel, cask',
 428: 'barrow, garden cart, lawn cart, wheelbarrow',
 429: 'baseball',
 430: 'basketball',
 431: 'bassinet',
 432: 'bassoon',
 433: 'bathing cap, swimming cap',
 434: 'bath towel',
 435: 'bathtub, bathing tub, bath, tub',
 436: 'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon',
 437: 'beacon, lighthouse, beacon light, pharos',
 438: 'beaker',
 439: 'bearskin, busby, shako',
 440: 'beer bottle',
 441: 'beer glass',
 442: 'bell cote, bell cot',
 443: 'bib',
 444: 'bicycle-built-for-two, tandem bicycle, tandem',
 445: 'bikini, two-piece',
 446: 'binder, ring-binder',
 447: 'binoculars, field glasses, opera glasses',
 448: 'birdhouse',
 449: 'boathouse',
 450: 'bobsled, bobsleigh, bob',
 451: 'bolo tie, bolo, bola tie, bola',
 452: 'bonnet, poke bonnet',
 453: 'bookcase',
 454: 'bookshop, bookstore, bookstall',
 455: 'bottlecap',
 456: 'bow',
 457: 'bow tie, bow-tie, bowtie',
 458: 'brass, memorial tablet, plaque',
 459: 'brassiere, bra, bandeau',
 460: 'breakwater, groin, groyne, mole, bulwark, seawall, jetty',
 461: 'breastplate, aegis, egis',
 462: 'broom',
 463: 'bucket, pail',
 464: 'buckle',
 465: 'bulletproof vest',
 466: 'bullet train, bullet',
 467: 'butcher shop, meat market',
 468: 'cab, hack, taxi, taxicab',
 469: 'caldron, cauldron',
 470: 'candle, taper, wax light',
 471: 'cannon',
 472: 'canoe',
 473: 'can opener, tin opener',
 474: 'cardigan',
 475: 'car mirror',
 476: 'carousel, carrousel, merry-go-round, roundabout, whirligig',
 477: "carpenter's kit, tool kit",
 478: 'carton',
 479: 'car wheel',
 480: 'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM',
 481: 'cassette',
 482: 'cassette player',
 483: 'castle',
 484: 'catamaran',
 485: 'CD player',
 486: 'cello, violoncello',
 487: 'cellular telephone, cellular phone, cellphone, cell, mobile phone',
 488: 'chain',
 489: 'chainlink fence',
 490: 'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour',
 491: 'chain saw, chainsaw',
 492: 'chest',
 493: 'chiffonier, commode',
 494: 'chime, bell, gong',
 495: 'china cabinet, china closet',
 496: 'Christmas stocking',
 497: 'church, church building',
 498: 'cinema, movie theater, movie theatre, movie house, picture palace',
 499: 'cleaver, meat cleaver, chopper',
 500: 'cliff dwelling',
 501: 'cloak',
 502: 'clog, geta, patten, sabot',
 503: 'cocktail shaker',
 504: 'coffee mug',
 505: 'coffeepot',
 506: 'coil, spiral, volute, whorl, helix',
 507: 'combination lock',
 508: 'computer keyboard, keypad',
 509: 'confectionery, confectionary, candy store',
 510: 'container ship, containership, container vessel',
 511: 'convertible',
 512: 'corkscrew, bottle screw',
 513: 'cornet, horn, trumpet, trump',
 514: 'cowboy boot',
 515: 'cowboy hat, ten-gallon hat',
 516: 'cradle',
 517: 'crane',
 518: 'crash helmet',
 519: 'crate',
 520: 'crib, cot',
 521: 'Crock Pot',
 522: 'croquet ball',
 523: 'crutch',
 524: 'cuirass',
 525: 'dam, dike, dyke',
 526: 'desk',
 527: 'desktop computer',
 528: 'dial telephone, dial phone',
 529: 'diaper, nappy, napkin',
 530: 'digital clock',
 531: 'digital watch',
 532: 'dining table, board',
 533: 'dishrag, dishcloth',
 534: 'dishwasher, dish washer, dishwashing machine',
 535: 'disk brake, disc brake',
 536: 'dock, dockage, docking facility',
 537: 'dogsled, dog sled, dog sleigh',
 538: 'dome',
 539: 'doormat, welcome mat',
 540: 'drilling platform, offshore rig',
 541: 'drum, membranophone, tympan',
 542: 'drumstick',
 543: 'dumbbell',
 544: 'Dutch oven',
 545: 'electric fan, blower',
 546: 'electric guitar',
 547: 'electric locomotive',
 548: 'entertainment center',
 549: 'envelope',
 550: 'espresso maker',
 551: 'face powder',
 552: 'feather boa, boa',
 553: 'file, file cabinet, filing cabinet',
 554: 'fireboat',
 555: 'fire engine, fire truck',
 556: 'fire screen, fireguard',
 557: 'flagpole, flagstaff',
 558: 'flute, transverse flute',
 559: 'folding chair',
 560: 'football helmet',
 561: 'forklift',
 562: 'fountain',
 563: 'fountain pen',
 564: 'four-poster',
 565: 'freight car',
 566: 'French horn, horn',
 567: 'frying pan, frypan, skillet',
 568: 'fur coat',
 569: 'garbage truck, dustcart',
 570: 'gasmask, respirator, gas helmet',
 571: 'gas pump, gasoline pump, petrol pump, island dispenser',
 572: 'goblet',
 573: 'go-kart',
 574: 'golf ball',
 575: 'golfcart, golf cart',
 576: 'gondola',
 577: 'gong, tam-tam',
 578: 'gown',
 579: 'grand piano, grand',
 580: 'greenhouse, nursery, glasshouse',
 581: 'grille, radiator grille',
 582: 'grocery store, grocery, food market, market',
 583: 'guillotine',
 584: 'hair slide',
 585: 'hair spray',
 586: 'half track',
 587: 'hammer',
 588: 'hamper',
 589: 'hand blower, blow dryer, blow drier, hair dryer, hair drier',
 590: 'hand-held computer, hand-held microcomputer',
 591: 'handkerchief, hankie, hanky, hankey',
 592: 'hard disc, hard disk, fixed disk',
 593: 'harmonica, mouth organ, harp, mouth harp',
 594: 'harp',
 595: 'harvester, reaper',
 596: 'hatchet',
 597: 'holster',
 598: 'home theater, home theatre',
 599: 'honeycomb',
 600: 'hook, claw',
 601: 'hoopskirt, crinoline',
 602: 'horizontal bar, high bar',
 603: 'horse cart, horse-cart',
 604: 'hourglass',
 605: 'iPod',
 606: 'iron, smoothing iron',
 607: "jack-o'-lantern",
 608: 'jean, blue jean, denim',
 609: 'jeep, landrover',
 610: 'jersey, T-shirt, tee shirt',
 611: 'jigsaw puzzle',
 612: 'jinrikisha, ricksha, rickshaw',
 613: 'joystick',
 614: 'kimono',
 615: 'knee pad',
 616: 'knot',
 617: 'lab coat, laboratory coat',
 618: 'ladle',
 619: 'lampshade, lamp shade',
 620: 'laptop, laptop computer',
 621: 'lawn mower, mower',
 622: 'lens cap, lens cover',
 623: 'letter opener, paper knife, paperknife',
 624: 'library',
 625: 'lifeboat',
 626: 'lighter, light, igniter, ignitor',
 627: 'limousine, limo',
 628: 'liner, ocean liner',
 629: 'lipstick, lip rouge',
 630: 'Loafer',
 631: 'lotion',
 632: 'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system',
 633: "loupe, jeweler's loupe",
 634: 'lumbermill, sawmill',
 635: 'magnetic compass',
 636: 'mailbag, postbag',
 637: 'mailbox, letter box',
 638: 'maillot',
 639: 'maillot, tank suit',
 640: 'manhole cover',
 641: 'maraca',
 642: 'marimba, xylophone',
 643: 'mask',
 644: 'matchstick',
 645: 'maypole',
 646: 'maze, labyrinth',
 647: 'measuring cup',
 648: 'medicine chest, medicine cabinet',
 649: 'megalith, megalithic structure',
 650: 'microphone, mike',
 651: 'microwave, microwave oven',
 652: 'military uniform',
 653: 'milk can',
 654: 'minibus',
 655: 'miniskirt, mini',
 656: 'minivan',
 657: 'missile',
 658: 'mitten',
 659: 'mixing bowl',
 660: 'mobile home, manufactured home',
 661: 'Model T',
 662: 'modem',
 663: 'monastery',
 664: 'monitor',
 665: 'moped',
 666: 'mortar',
 667: 'mortarboard',
 668: 'mosque',
 669: 'mosquito net',
 670: 'motor scooter, scooter',
 671: 'mountain bike, all-terrain bike, off-roader',
 672: 'mountain tent',
 673: 'mouse, computer mouse',
 674: 'mousetrap',
 675: 'moving van',
 676: 'muzzle',
 677: 'nail',
 678: 'neck brace',
 679: 'necklace',
 680: 'nipple',
 681: 'notebook, notebook computer',
 682: 'obelisk',
 683: 'oboe, hautboy, hautbois',
 684: 'ocarina, sweet potato',
 685: 'odometer, hodometer, mileometer, milometer',
 686: 'oil filter',
 687: 'organ, pipe organ',
 688: 'oscilloscope, scope, cathode-ray oscilloscope, CRO',
 689: 'overskirt',
 690: 'oxcart',
 691: 'oxygen mask',
 692: 'packet',
 693: 'paddle, boat paddle',
 694: 'paddlewheel, paddle wheel',
 695: 'padlock',
 696: 'paintbrush',
 697: "pajama, pyjama, pj's, jammies",
 698: 'palace',
 699: 'panpipe, pandean pipe, syrinx',
 700: 'paper towel',
 701: 'parachute, chute',
 702: 'parallel bars, bars',
 703: 'park bench',
 704: 'parking meter',
 705: 'passenger car, coach, carriage',
 706: 'patio, terrace',
 707: 'pay-phone, pay-station',
 708: 'pedestal, plinth, footstall',
 709: 'pencil box, pencil case',
 710: 'pencil sharpener',
 711: 'perfume, essence',
 712: 'Petri dish',
 713: 'photocopier',
 714: 'pick, plectrum, plectron',
 715: 'pickelhaube',
 716: 'picket fence, paling',
 717: 'pickup, pickup truck',
 718: 'pier',
 719: 'piggy bank, penny bank',
 720: 'pill bottle',
 721: 'pillow',
 722: 'ping-pong ball',
 723: 'pinwheel',
 724: 'pirate, pirate ship',
 725: 'pitcher, ewer',
 726: "plane, carpenter's plane, woodworking plane",
 727: 'planetarium',
 728: 'plastic bag',
 729: 'plate rack',
 730: 'plow, plough',
 731: "plunger, plumber's helper",
 732: 'Polaroid camera, Polaroid Land camera',
 733: 'pole',
 734: 'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria',
 735: 'poncho',
 736: 'pool table, billiard table, snooker table',
 737: 'pop bottle, soda bottle',
 738: 'pot, flowerpot',
 739: "potter's wheel",
 740: 'power drill',
 741: 'prayer rug, prayer mat',
 742: 'printer',
 743: 'prison, prison house',
 744: 'projectile, missile',
 745: 'projector',
 746: 'puck, hockey puck',
 747: 'punching bag, punch bag, punching ball, punchball',
 748: 'purse',
 749: 'quill, quill pen',
 750: 'quilt, comforter, comfort, puff',
 751: 'racer, race car, racing car',
 752: 'racket, racquet',
 753: 'radiator',
 754: 'radio, wireless',
 755: 'radio telescope, radio reflector',
 756: 'rain barrel',
 757: 'recreational vehicle, RV, R.V.',
 758: 'reel',
 759: 'reflex camera',
 760: 'refrigerator, icebox',
 761: 'remote control, remote',
 762: 'restaurant, eating house, eating place, eatery',
 763: 'revolver, six-gun, six-shooter',
 764: 'rifle',
 765: 'rocking chair, rocker',
 766: 'rotisserie',
 767: 'rubber eraser, rubber, pencil eraser',
 768: 'rugby ball',
 769: 'rule, ruler',
 770: 'running shoe',
 771: 'safe',
 772: 'safety pin',
 773: 'saltshaker, salt shaker',
 774: 'sandal',
 775: 'sarong',
 776: 'sax, saxophone',
 777: 'scabbard',
 778: 'scale, weighing machine',
 779: 'school bus',
 780: 'schooner',
 781: 'scoreboard',
 782: 'screen, CRT screen',
 783: 'screw',
 784: 'screwdriver',
 785: 'seat belt, seatbelt',
 786: 'sewing machine',
 787: 'shield, buckler',
 788: 'shoe shop, shoe-shop, shoe store',
 789: 'shoji',
 790: 'shopping basket',
 791: 'shopping cart',
 792: 'shovel',
 793: 'shower cap',
 794: 'shower curtain',
 795: 'ski',
 796: 'ski mask',
 797: 'sleeping bag',
 798: 'slide rule, slipstick',
 799: 'sliding door',
 800: 'slot, one-armed bandit',
 801: 'snorkel',
 802: 'snowmobile',
 803: 'snowplow, snowplough',
 804: 'soap dispenser',
 805: 'soccer ball',
 806: 'sock',
 807: 'solar dish, solar collector, solar furnace',
 808: 'sombrero',
 809: 'soup bowl',
 810: 'space bar',
 811: 'space heater',
 812: 'space shuttle',
 813: 'spatula',
 814: 'speedboat',
 815: "spider web, spider's web",
 816: 'spindle',
 817: 'sports car, sport car',
 818: 'spotlight, spot',
 819: 'stage',
 820: 'steam locomotive',
 821: 'steel arch bridge',
 822: 'steel drum',
 823: 'stethoscope',
 824: 'stole',
 825: 'stone wall',
 826: 'stopwatch, stop watch',
 827: 'stove',
 828: 'strainer',
 829: 'streetcar, tram, tramcar, trolley, trolley car',
 830: 'stretcher',
 831: 'studio couch, day bed',
 832: 'stupa, tope',
 833: 'submarine, pigboat, sub, U-boat',
 834: 'suit, suit of clothes',
 835: 'sundial',
 836: 'sunglass',
 837: 'sunglasses, dark glasses, shades',
 838: 'sunscreen, sunblock, sun blocker',
 839: 'suspension bridge',
 840: 'swab, swob, mop',
 841: 'sweatshirt',
 842: 'swimming trunks, bathing trunks',
 843: 'swing',
 844: 'switch, electric switch, electrical switch',
 845: 'syringe',
 846: 'table lamp',
 847: 'tank, army tank, armored combat vehicle, armoured combat vehicle',
 848: 'tape player',
 849: 'teapot',
 850: 'teddy, teddy bear',
 851: 'television, television system',
 852: 'tennis ball',
 853: 'thatch, thatched roof',
 854: 'theater curtain, theatre curtain',
 855: 'thimble',
 856: 'thresher, thrasher, threshing machine',
 857: 'throne',
 858: 'tile roof',
 859: 'toaster',
 860: 'tobacco shop, tobacconist shop, tobacconist',
 861: 'toilet seat',
 862: 'torch',
 863: 'totem pole',
 864: 'tow truck, tow car, wrecker',
 865: 'toyshop',
 866: 'tractor',
 867: 'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi',
 868: 'tray',
 869: 'trench coat',
 870: 'tricycle, trike, velocipede',
 871: 'trimaran',
 872: 'tripod',
 873: 'triumphal arch',
 874: 'trolleybus, trolley coach, trackless trolley',
 875: 'trombone',
 876: 'tub, vat',
 877: 'turnstile',
 878: 'typewriter keyboard',
 879: 'umbrella',
 880: 'unicycle, monocycle',
 881: 'upright, upright piano',
 882: 'vacuum, vacuum cleaner',
 883: 'vase',
 884: 'vault',
 885: 'velvet',
 886: 'vending machine',
 887: 'vestment',
 888: 'viaduct',
 889: 'violin, fiddle',
 890: 'volleyball',
 891: 'waffle iron',
 892: 'wall clock',
 893: 'wallet, billfold, notecase, pocketbook',
 894: 'wardrobe, closet, press',
 895: 'warplane, military plane',
 896: 'washbasin, handbasin, washbowl, lavabo, wash-hand basin',
 897: 'washer, automatic washer, washing machine',
 898: 'water bottle',
 899: 'water jug',
 900: 'water tower',
 901: 'whiskey jug',
 902: 'whistle',
 903: 'wig',
 904: 'window screen',
 905: 'window shade',
 906: 'Windsor tie',
 907: 'wine bottle',
 908: 'wing',
 909: 'wok',
 910: 'wooden spoon',
 911: 'wool, woolen, woollen',
 912: 'worm fence, snake fence, snake-rail fence, Virginia fence',
 913: 'wreck',
 914: 'yawl',
 915: 'yurt',
 916: 'web site, website, internet site, site',
 917: 'comic book',
 918: 'crossword puzzle, crossword',
 919: 'street sign',
 920: 'traffic light, traffic signal, stoplight',
 921: 'book jacket, dust cover, dust jacket, dust wrapper',
 922: 'menu',
 923: 'plate',
 924: 'guacamole',
 925: 'consomme',
 926: 'hot pot, hotpot',
 927: 'trifle',
 928: 'ice cream, icecream',
 929: 'ice lolly, lolly, lollipop, popsicle',
 930: 'French loaf',
 931: 'bagel, beigel',
 932: 'pretzel',
 933: 'cheeseburger',
 934: 'hotdog, hot dog, red hot',
 935: 'mashed potato',
 936: 'head cabbage',
 937: 'broccoli',
 938: 'cauliflower',
 939: 'zucchini, courgette',
 940: 'spaghetti squash',
 941: 'acorn squash',
 942: 'butternut squash',
 943: 'cucumber, cuke',
 944: 'artichoke, globe artichoke',
 945: 'bell pepper',
 946: 'cardoon',
 947: 'mushroom',
 948: 'Granny Smith',
 949: 'strawberry',
 950: 'orange',
 951: 'lemon',
 952: 'fig',
 953: 'pineapple, ananas',
 954: 'banana',
 955: 'jackfruit, jak, jack',
 956: 'custard apple',
 957: 'pomegranate',
 958: 'hay',
 959: 'carbonara',
 960: 'chocolate sauce, chocolate syrup',
 961: 'dough',
 962: 'meat loaf, meatloaf',
 963: 'pizza, pizza pie',
 964: 'potpie',
 965: 'burrito',
 966: 'red wine',
 967: 'espresso',
 968: 'cup',
 969: 'eggnog',
 970: 'alp',
 971: 'bubble',
 972: 'cliff, drop, drop-off',
 973: 'coral reef',
 974: 'geyser',
 975: 'lakeside, lakeshore',
 976: 'promontory, headland, head, foreland',
 977: 'sandbar, sand bar',
 978: 'seashore, coast, seacoast, sea-coast',
 979: 'valley, vale',
 980: 'volcano',
 981: 'ballplayer, baseball player',
 982: 'groom, bridegroom',
 983: 'scuba diver',
 984: 'rapeseed',
 985: 'daisy',
 986: "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum",
 987: 'corn',
 988: 'acorn',
 989: 'hip, rose hip, rosehip',
 990: 'buckeye, horse chestnut, conker',
 991: 'coral fungus',
 992: 'agaric',
 993: 'gyromitra',
 994: 'stinkhorn, carrion fungus',
 995: 'earthstar',
 996: 'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa',
 997: 'bolete',
 998: 'ear, spike, capitulum',
 999: 'toilet tissue, toilet paper, bathroom tissue'}

imagenet_label2class = {0: 'tench',
 1: 'goldfish',
 2: 'white_shark',
 3: 'tiger_shark',
 4: 'hammerhead',
 5: 'electric_ray',
 6: 'stingray',
 7: 'cock',
 8: 'hen',
 9: 'ostrich',
 10: 'brambling',
 11: 'goldfinch',
 12: 'house_finch',
 13: 'junco',
 14: 'indigo_bunting',
 15: 'robin',
 16: 'bulbul',
 17: 'jay',
 18: 'magpie',
 19: 'chickadee',
 20: 'water_ouzel',
 21: 'kite',
 22: 'bald_eagle',
 23: 'vulture',
 24: 'great_grey_owl',
 25: 'European_fire_salamander',
 26: 'common_newt',
 27: 'eft',
 28: 'spotted_salamander',
 29: 'axolotl',
 30: 'bullfrog',
 31: 'tree_frog',
 32: 'tailed_frog',
 33: 'loggerhead',
 34: 'leatherback_turtle',
 35: 'mud_turtle',
 36: 'terrapin',
 37: 'box_turtle',
 38: 'banded_gecko',
 39: 'common_iguana',
 40: 'American_chameleon',
 41: 'whiptail',
 42: 'agama',
 43: 'frilled_lizard',
 44: 'alligator_lizard',
 45: 'Gila_monster',
 46: 'green_lizard',
 47: 'African_chameleon',
 48: 'Komodo_dragon',
 49: 'African_crocodile',
 50: 'American_alligator',
 51: 'triceratops',
 52: 'thunder_snake',
 53: 'ringneck_snake',
 54: 'hognose_snake',
 55: 'green_snake',
 56: 'king_snake',
 57: 'garter_snake',
 58: 'water_snake',
 59: 'vine_snake',
 60: 'night_snake',
 61: 'boa_constrictor',
 62: 'rock_python',
 63: 'Indian_cobra',
 64: 'green_mamba',
 65: 'sea_snake',
 66: 'horned_viper',
 67: 'diamondback',
 68: 'sidewinder',
 69: 'trilobite',
 70: 'harvestman',
 71: 'scorpion',
 72: 'black_and_gold_garden_spider',
 73: 'barn_spider',
 74: 'garden_spider',
 75: 'black_widow',
 76: 'tarantula',
 77: 'wolf_spider',
 78: 'tick',
 79: 'centipede',
 80: 'black_grouse',
 81: 'ptarmigan',
 82: 'ruffed_grouse',
 83: 'prairie_chicken',
 84: 'peacock',
 85: 'quail',
 86: 'partridge',
 87: 'African_grey',
 88: 'macaw',
 89: 'sulphur-crested_cockatoo',
 90: 'lorikeet',
 91: 'coucal',
 92: 'bee_eater',
 93: 'hornbill',
 94: 'hummingbird',
 95: 'jacamar',
 96: 'toucan',
 97: 'drake',
 98: 'red-breasted_merganser',
 99: 'goose',
 100: 'black_swan',
 101: 'tusker',
 102: 'echidna',
 103: 'platypus',
 104: 'wallaby',
 105: 'koala',
 106: 'wombat',
 107: 'jellyfish',
 108: 'sea_anemone',
 109: 'brain_coral',
 110: 'flatworm',
 111: 'nematode',
 112: 'conch',
 113: 'snail',
 114: 'slug',
 115: 'sea_slug',
 116: 'chiton',
 117: 'chambered_nautilus',
 118: 'Dungeness_crab',
 119: 'rock_crab',
 120: 'fiddler_crab',
 121: 'king_crab',
 122: 'American_lobster',
 123: 'spiny_lobster',
 124: 'crayfish',
 125: 'hermit_crab',
 126: 'isopod',
 127: 'white_stork',
 128: 'black_stork',
 129: 'spoonbill',
 130: 'flamingo',
 131: 'little_blue_heron',
 132: 'American_egret',
 133: 'bittern',
 134: 'crane',
 135: 'limpkin',
 136: 'European_gallinule',
 137: 'American_coot',
 138: 'bustard',
 139: 'ruddy_turnstone',
 140: 'red-backed_sandpiper',
 141: 'redshank',
 142: 'dowitcher',
 143: 'oystercatcher',
 144: 'pelican',
 145: 'king_penguin',
 146: 'albatross',
 147: 'grey_whale',
 148: 'killer_whale',
 149: 'dugong',
 150: 'sea_lion',
 151: 'Chihuahua',
 152: 'Japanese_spaniel',
 153: 'Maltese_dog',
 154: 'Pekinese',
 155: 'Shih-Tzu',
 156: 'Blenheim_spaniel',
 157: 'papillon',
 158: 'toy_terrier',
 159: 'Rhodesian_ridgeback',
 160: 'Afghan_hound',
 161: 'basset',
 162: 'beagle',
 163: 'bloodhound',
 164: 'bluetick',
 165: 'black-and-tan_coonhound',
 166: 'Walker_hound',
 167: 'English_foxhound',
 168: 'redbone',
 169: 'borzoi',
 170: 'Irish_wolfhound',
 171: 'Italian_greyhound',
 172: 'whippet',
 173: 'Ibizan_hound',
 174: 'Norwegian_elkhound',
 175: 'otterhound',
 176: 'Saluki',
 177: 'Scottish_deerhound',
 178: 'Weimaraner',
 179: 'Staffordshire_bullterrier',
 180: 'American_Staffordshire_terrier',
 181: 'Bedlington_terrier',
 182: 'Border_terrier',
 183: 'Kerry_blue_terrier',
 184: 'Irish_terrier',
 185: 'Norfolk_terrier',
 186: 'Norwich_terrier',
 187: 'Yorkshire_terrier',
 188: 'wire-haired_fox_terrier',
 189: 'Lakeland_terrier',
 190: 'Sealyham_terrier',
 191: 'Airedale',
 192: 'cairn',
 193: 'Australian_terrier',
 194: 'Dandie_Dinmont',
 195: 'Boston_bull',
 196: 'miniature_schnauzer',
 197: 'giant_schnauzer',
 198: 'standard_schnauzer',
 199: 'Scotch_terrier',
 200: 'Tibetan_terrier',
 201: 'silky_terrier',
 202: 'soft-coated_wheaten_terrier',
 203: 'West_Highland_white_terrier',
 204: 'Lhasa',
 205: 'flat-coated_retriever',
 206: 'curly-coated_retriever',
 207: 'golden_retriever',
 208: 'Labrador_retriever',
 209: 'Chesapeake_Bay_retriever',
 210: 'German_short-haired_pointer',
 211: 'vizsla',
 212: 'English_setter',
 213: 'Irish_setter',
 214: 'Gordon_setter',
 215: 'Brittany_spaniel',
 216: 'clumber',
 217: 'English_springer',
 218: 'Welsh_springer_spaniel',
 219: 'cocker_spaniel',
 220: 'Sussex_spaniel',
 221: 'Irish_water_spaniel',
 222: 'kuvasz',
 223: 'schipperke',
 224: 'groenendael',
 225: 'malinois',
 226: 'briard',
 227: 'kelpie',
 228: 'komondor',
 229: 'Old_English_sheepdog',
 230: 'Shetland_sheepdog',
 231: 'collie',
 232: 'Border_collie',
 233: 'Bouvier_des_Flandres',
 234: 'Rottweiler',
 235: 'German_shepherd',
 236: 'Doberman',
 237: 'miniature_pinscher',
 238: 'Greater_Swiss_Mountain_dog',
 239: 'Bernese_mountain_dog',
 240: 'Appenzeller',
 241: 'EntleBucher',
 242: 'boxer',
 243: 'bull_mastiff',
 244: 'Tibetan_mastiff',
 245: 'French_bulldog',
 246: 'Great_Dane',
 247: 'Saint_Bernard',
 248: 'Eskimo_dog',
 249: 'malamute',
 250: 'Siberian_husky',
 251: 'dalmatian',
 252: 'affenpinscher',
 253: 'basenji',
 254: 'pug',
 255: 'Leonberg',
 256: 'Newfoundland',
 257: 'Great_Pyrenees',
 258: 'Samoyed',
 259: 'Pomeranian',
 260: 'chow',
 261: 'keeshond',
 262: 'Brabancon_griffon',
 263: 'Pembroke',
 264: 'Cardigan',
 265: 'toy_poodle',
 266: 'miniature_poodle',
 267: 'standard_poodle',
 268: 'Mexican_hairless',
 269: 'timber_wolf',
 270: 'white_wolf',
 271: 'red_wolf',
 272: 'coyote',
 273: 'dingo',
 274: 'dhole',
 275: 'African_hunting_dog',
 276: 'hyena',
 277: 'red_fox',
 278: 'kit_fox',
 279: 'Arctic_fox',
 280: 'grey_fox',
 281: 'tabby',
 282: 'tiger_cat',
 283: 'Persian_cat',
 284: 'Siamese_cat',
 285: 'Egyptian_cat',
 286: 'cougar',
 287: 'lynx',
 288: 'leopard',
 289: 'snow_leopard',
 290: 'jaguar',
 291: 'lion',
 292: 'tiger',
 293: 'cheetah',
 294: 'brown_bear',
 295: 'American_black_bear',
 296: 'ice_bear',
 297: 'sloth_bear',
 298: 'mongoose',
 299: 'meerkat',
 300: 'tiger_beetle',
 301: 'ladybug',
 302: 'ground_beetle',
 303: 'long-horned_beetle',
 304: 'leaf_beetle',
 305: 'dung_beetle',
 306: 'rhinoceros_beetle',
 307: 'weevil',
 308: 'fly',
 309: 'bee',
 310: 'ant',
 311: 'grasshopper',
 312: 'cricket',
 313: 'walking_stick',
 314: 'cockroach',
 315: 'mantis',
 316: 'cicada',
 317: 'leafhopper',
 318: 'lacewing',
 319: 'dragonfly',
 320: 'damselfly',
 321: 'admiral',
 322: 'ringlet',
 323: 'monarch',
 324: 'cabbage_butterfly',
 325: 'sulphur_butterfly',
 326: 'lycaenid',
 327: 'starfish',
 328: 'sea_urchin',
 329: 'sea_cucumber',
 330: 'wood_rabbit',
 331: 'hare',
 332: 'Angora',
 333: 'hamster',
 334: 'porcupine',
 335: 'fox_squirrel',
 336: 'marmot',
 337: 'beaver',
 338: 'guinea_pig',
 339: 'sorrel',
 340: 'zebra',
 341: 'hog',
 342: 'wild_boar',
 343: 'warthog',
 344: 'hippopotamus',
 345: 'ox',
 346: 'water_buffalo',
 347: 'bison',
 348: 'ram',
 349: 'bighorn',
 350: 'ibex',
 351: 'hartebeest',
 352: 'impala',
 353: 'gazelle',
 354: 'Arabian_camel',
 355: 'llama',
 356: 'weasel',
 357: 'mink',
 358: 'polecat',
 359: 'black-footed_ferret',
 360: 'otter',
 361: 'skunk',
 362: 'badger',
 363: 'armadillo',
 364: 'three-toed_sloth',
 365: 'orangutan',
 366: 'gorilla',
 367: 'chimpanzee',
 368: 'gibbon',
 369: 'siamang',
 370: 'guenon',
 371: 'patas',
 372: 'baboon',
 373: 'macaque',
 374: 'langur',
 375: 'colobus',
 376: 'proboscis_monkey',
 377: 'marmoset',
 378: 'capuchin',
 379: 'howler_monkey',
 380: 'titi',
 381: 'spider_monkey',
 382: 'squirrel_monkey',
 383: 'Madagascar_cat',
 384: 'indri',
 385: 'Indian_elephant',
 386: 'African_elephant',
 387: 'lesser_panda',
 388: 'giant_panda',
 389: 'barracouta',
 390: 'eel',
 391: 'coho',
 392: 'rock_beauty',
 393: 'anemone_fish',
 394: 'sturgeon',
 395: 'gar',
 396: 'lionfish',
 397: 'puffer',
 398: 'abacus',
 399: 'abaya',
 400: 'academic_gown',
 401: 'accordion',
 402: 'acoustic_guitar',
 403: 'aircraft_carrier',
 404: 'airliner',
 405: 'airship',
 406: 'altar',
 407: 'ambulance',
 408: 'amphibian',
 409: 'analog_clock',
 410: 'apiary',
 411: 'apron',
 412: 'ashcan',
 413: 'assault_rifle',
 414: 'backpack',
 415: 'bakery',
 416: 'balance_beam',
 417: 'balloon',
 418: 'ballpoint',
 419: 'Band_Aid',
 420: 'banjo',
 421: 'bannister',
 422: 'barbell',
 423: 'barber_chair',
 424: 'barbershop',
 425: 'barn',
 426: 'barometer',
 427: 'barrel',
 428: 'barrow',
 429: 'baseball',
 430: 'basketball',
 431: 'bassinet',
 432: 'bassoon',
 433: 'bathing_cap',
 434: 'bath_towel',
 435: 'bathtub',
 436: 'beach_wagon',
 437: 'beacon',
 438: 'beaker',
 439: 'bearskin',
 440: 'beer_bottle',
 441: 'beer_glass',
 442: 'bell_cote',
 443: 'bib',
 444: 'bicycle-built-for-two',
 445: 'bikini',
 446: 'binder',
 447: 'binoculars',
 448: 'birdhouse',
 449: 'boathouse',
 450: 'bobsled',
 451: 'bolo_tie',
 452: 'bonnet',
 453: 'bookcase',
 454: 'bookshop',
 455: 'bottlecap',
 456: 'bow',
 457: 'bow_tie',
 458: 'brass',
 459: 'brassiere',
 460: 'breakwater',
 461: 'breastplate',
 462: 'broom',
 463: 'bucket',
 464: 'buckle',
 465: 'bulletproof_vest',
 466: 'bullet_train',
 467: 'butcher_shop',
 468: 'cab',
 469: 'caldron',
 470: 'candle',
 471: 'cannon',
 472: 'canoe',
 473: 'can_opener',
 474: 'cardigan',
 475: 'car_mirror',
 476: 'carousel',
 477: "carpenter's_kit",
 478: 'carton',
 479: 'car_wheel',
 480: 'cash_machine',
 481: 'cassette',
 482: 'cassette_player',
 483: 'castle',
 484: 'catamaran',
 485: 'CD_player',
 486: 'cello',
 487: 'cellular_telephone',
 488: 'chain',
 489: 'chainlink_fence',
 490: 'chain_mail',
 491: 'chain_saw',
 492: 'chest',
 493: 'chiffonier',
 494: 'chime',
 495: 'china_cabinet',
 496: 'Christmas_stocking',
 497: 'church',
 498: 'cinema',
 499: 'cleaver',
 500: 'cliff_dwelling',
 501: 'cloak',
 502: 'clog',
 503: 'cocktail_shaker',
 504: 'coffee_mug',
 505: 'coffeepot',
 506: 'coil',
 507: 'combination_lock',
 508: 'computer_keyboard',
 509: 'confectionery',
 510: 'container_ship',
 511: 'convertible',
 512: 'corkscrew',
 513: 'cornet',
 514: 'cowboy_boot',
 515: 'cowboy_hat',
 516: 'cradle',
 517: 'crane',
 518: 'crash_helmet',
 519: 'crate',
 520: 'crib',
 521: 'Crock_Pot',
 522: 'croquet_ball',
 523: 'crutch',
 524: 'cuirass',
 525: 'dam',
 526: 'desk',
 527: 'desktop_computer',
 528: 'dial_telephone',
 529: 'diaper',
 530: 'digital_clock',
 531: 'digital_watch',
 532: 'dining_table',
 533: 'dishrag',
 534: 'dishwasher',
 535: 'disk_brake',
 536: 'dock',
 537: 'dogsled',
 538: 'dome',
 539: 'doormat',
 540: 'drilling_platform',
 541: 'drum',
 542: 'drumstick',
 543: 'dumbbell',
 544: 'Dutch_oven',
 545: 'electric_fan',
 546: 'electric_guitar',
 547: 'electric_locomotive',
 548: 'entertainment_center',
 549: 'envelope',
 550: 'espresso_maker',
 551: 'face_powder',
 552: 'feather_boa',
 553: 'file',
 554: 'fireboat',
 555: 'fire_engine',
 556: 'fire_screen',
 557: 'flagpole',
 558: 'flute',
 559: 'folding_chair',
 560: 'football_helmet',
 561: 'forklift',
 562: 'fountain',
 563: 'fountain_pen',
 564: 'four-poster',
 565: 'freight_car',
 566: 'French_horn',
 567: 'frying_pan',
 568: 'fur_coat',
 569: 'garbage_truck',
 570: 'gasmask',
 571: 'gas_pump',
 572: 'goblet',
 573: 'go-kart',
 574: 'golf_ball',
 575: 'golfcart',
 576: 'gondola',
 577: 'gong',
 578: 'gown',
 579: 'grand_piano',
 580: 'greenhouse',
 581: 'grille',
 582: 'grocery_store',
 583: 'guillotine',
 584: 'hair_slide',
 585: 'hair_spray',
 586: 'half_track',
 587: 'hammer',
 588: 'hamper',
 589: 'hand_blower',
 590: 'hand-held_computer',
 591: 'handkerchief',
 592: 'hard_disc',
 593: 'harmonica',
 594: 'harp',
 595: 'harvester',
 596: 'hatchet',
 597: 'holster',
 598: 'home_theater',
 599: 'honeycomb',
 600: 'hook',
 601: 'hoopskirt',
 602: 'horizontal_bar',
 603: 'horse_cart',
 604: 'hourglass',
 605: 'iPod',
 606: 'iron',
 607: "jack-o'-lantern",
 608: 'jean',
 609: 'jeep',
 610: 'jersey',
 611: 'jigsaw_puzzle',
 612: 'jinrikisha',
 613: 'joystick',
 614: 'kimono',
 615: 'knee_pad',
 616: 'knot',
 617: 'lab_coat',
 618: 'ladle',
 619: 'lampshade',
 620: 'laptop',
 621: 'lawn_mower',
 622: 'lens_cap',
 623: 'letter_opener',
 624: 'library',
 625: 'lifeboat',
 626: 'lighter',
 627: 'limousine',
 628: 'liner',
 629: 'lipstick',
 630: 'Loafer',
 631: 'lotion',
 632: 'loudspeaker',
 633: 'loupe',
 634: 'lumbermill',
 635: 'magnetic_compass',
 636: 'mailbag',
 637: 'mailbox',
 638: 'maillot',
 639: 'maillot',
 640: 'manhole_cover',
 641: 'maraca',
 642: 'marimba',
 643: 'mask',
 644: 'matchstick',
 645: 'maypole',
 646: 'maze',
 647: 'measuring_cup',
 648: 'medicine_chest',
 649: 'megalith',
 650: 'microphone',
 651: 'microwave',
 652: 'military_uniform',
 653: 'milk_can',
 654: 'minibus',
 655: 'miniskirt',
 656: 'minivan',
 657: 'missile',
 658: 'mitten',
 659: 'mixing_bowl',
 660: 'mobile_home',
 661: 'Model_T',
 662: 'modem',
 663: 'monastery',
 664: 'monitor',
 665: 'moped',
 666: 'mortar',
 667: 'mortarboard',
 668: 'mosque',
 669: 'mosquito_net',
 670: 'motor_scooter',
 671: 'mountain_bike',
 672: 'mountain_tent',
 673: 'mouse',
 674: 'mousetrap',
 675: 'moving_van',
 676: 'muzzle',
 677: 'nail',
 678: 'neck_brace',
 679: 'necklace',
 680: 'nipple',
 681: 'notebook',
 682: 'obelisk',
 683: 'oboe',
 684: 'ocarina',
 685: 'odometer',
 686: 'oil_filter',
 687: 'organ',
 688: 'oscilloscope',
 689: 'overskirt',
 690: 'oxcart',
 691: 'oxygen_mask',
 692: 'packet',
 693: 'paddle',
 694: 'paddlewheel',
 695: 'padlock',
 696: 'paintbrush',
 697: 'pajama',
 698: 'palace',
 699: 'panpipe',
 700: 'paper_towel',
 701: 'parachute',
 702: 'parallel_bars',
 703: 'park_bench',
 704: 'parking_meter',
 705: 'passenger_car',
 706: 'patio',
 707: 'pay-phone',
 708: 'pedestal',
 709: 'pencil_box',
 710: 'pencil_sharpener',
 711: 'perfume',
 712: 'Petri_dish',
 713: 'photocopier',
 714: 'pick',
 715: 'pickelhaube',
 716: 'picket_fence',
 717: 'pickup',
 718: 'pier',
 719: 'piggy_bank',
 720: 'pill_bottle',
 721: 'pillow',
 722: 'ping-pong_ball',
 723: 'pinwheel',
 724: 'pirate',
 725: 'pitcher',
 726: 'plane',
 727: 'planetarium',
 728: 'plastic_bag',
 729: 'plate_rack',
 730: 'plow',
 731: 'plunger',
 732: 'Polaroid_camera',
 733: 'pole',
 734: 'police_van',
 735: 'poncho',
 736: 'pool_table',
 737: 'pop_bottle',
 738: 'pot',
 739: "potter's_wheel",
 740: 'power_drill',
 741: 'prayer_rug',
 742: 'printer',
 743: 'prison',
 744: 'projectile',
 745: 'projector',
 746: 'puck',
 747: 'punching_bag',
 748: 'purse',
 749: 'quill',
 750: 'quilt',
 751: 'racer',
 752: 'racket',
 753: 'radiator',
 754: 'radio',
 755: 'radio_telescope',
 756: 'rain_barrel',
 757: 'recreational_vehicle',
 758: 'reel',
 759: 'reflex_camera',
 760: 'refrigerator',
 761: 'remote_control',
 762: 'restaurant',
 763: 'revolver',
 764: 'rifle',
 765: 'rocking_chair',
 766: 'rotisserie',
 767: 'rubber_eraser',
 768: 'rugby_ball',
 769: 'rule',
 770: 'running_shoe',
 771: 'safe',
 772: 'safety_pin',
 773: 'saltshaker',
 774: 'sandal',
 775: 'sarong',
 776: 'sax',
 777: 'scabbard',
 778: 'scale',
 779: 'school_bus',
 780: 'schooner',
 781: 'scoreboard',
 782: 'screen',
 783: 'screw',
 784: 'screwdriver',
 785: 'seat_belt',
 786: 'sewing_machine',
 787: 'shield',
 788: 'shoe_shop',
 789: 'shoji',
 790: 'shopping_basket',
 791: 'shopping_cart',
 792: 'shovel',
 793: 'shower_cap',
 794: 'shower_curtain',
 795: 'ski',
 796: 'ski_mask',
 797: 'sleeping_bag',
 798: 'slide_rule',
 799: 'sliding_door',
 800: 'slot',
 801: 'snorkel',
 802: 'snowmobile',
 803: 'snowplow',
 804: 'soap_dispenser',
 805: 'soccer_ball',
 806: 'sock',
 807: 'solar_dish',
 808: 'sombrero',
 809: 'soup_bowl',
 810: 'space_bar',
 811: 'space_heater',
 812: 'space_shuttle',
 813: 'spatula',
 814: 'speedboat',
 815: 'spider_web',
 816: 'spindle',
 817: 'sports_car',
 818: 'spotlight',
 819: 'stage',
 820: 'steam_locomotive',
 821: 'steel_arch_bridge',
 822: 'steel_drum',
 823: 'stethoscope',
 824: 'stole',
 825: 'stone_wall',
 826: 'stopwatch',
 827: 'stove',
 828: 'strainer',
 829: 'streetcar',
 830: 'stretcher',
 831: 'studio_couch',
 832: 'stupa',
 833: 'submarine',
 834: 'suit',
 835: 'sundial',
 836: 'sunglass',
 837: 'sunglasses',
 838: 'sunscreen',
 839: 'suspension_bridge',
 840: 'swab',
 841: 'sweatshirt',
 842: 'swimming_trunks',
 843: 'swing',
 844: 'switch',
 845: 'syringe',
 846: 'table_lamp',
 847: 'tank',
 848: 'tape_player',
 849: 'teapot',
 850: 'teddy',
 851: 'television',
 852: 'tennis_ball',
 853: 'thatch',
 854: 'theater_curtain',
 855: 'thimble',
 856: 'thresher',
 857: 'throne',
 858: 'tile_roof',
 859: 'toaster',
 860: 'tobacco_shop',
 861: 'toilet_seat',
 862: 'torch',
 863: 'totem_pole',
 864: 'tow_truck',
 865: 'toyshop',
 866: 'tractor',
 867: 'trailer_truck',
 868: 'tray',
 869: 'trench_coat',
 870: 'tricycle',
 871: 'trimaran',
 872: 'tripod',
 873: 'triumphal_arch',
 874: 'trolleybus',
 875: 'trombone',
 876: 'tub',
 877: 'turnstile',
 878: 'typewriter_keyboard',
 879: 'umbrella',
 880: 'unicycle',
 881: 'upright',
 882: 'vacuum',
 883: 'vase',
 884: 'vault',
 885: 'velvet',
 886: 'vending_machine',
 887: 'vestment',
 888: 'viaduct',
 889: 'violin',
 890: 'volleyball',
 891: 'waffle_iron',
 892: 'wall_clock',
 893: 'wallet',
 894: 'wardrobe',
 895: 'warplane',
 896: 'washbasin',
 897: 'washer',
 898: 'water_bottle',
 899: 'water_jug',
 900: 'water_tower',
 901: 'whiskey_jug',
 902: 'whistle',
 903: 'wig',
 904: 'window_screen',
 905: 'window_shade',
 906: 'Windsor_tie',
 907: 'wine_bottle',
 908: 'wing',
 909: 'wok',
 910: 'wooden_spoon',
 911: 'wool',
 912: 'worm_fence',
 913: 'wreck',
 914: 'yawl',
 915: 'yurt',
 916: 'web_site',
 917: 'comic_book',
 918: 'crossword_puzzle',
 919: 'street_sign',
 920: 'traffic_light',
 921: 'book_jacket',
 922: 'menu',
 923: 'plate',
 924: 'guacamole',
 925: 'consomme',
 926: 'hot_pot',
 927: 'trifle',
 928: 'ice_cream',
 929: 'ice_lolly',
 930: 'French_loaf',
 931: 'bagel',
 932: 'pretzel',
 933: 'cheeseburger',
 934: 'hotdog',
 935: 'mashed_potato',
 936: 'head_cabbage',
 937: 'broccoli',
 938: 'cauliflower',
 939: 'zucchini',
 940: 'spaghetti_squash',
 941: 'acorn_squash',
 942: 'butternut_squash',
 943: 'cucumber',
 944: 'artichoke',
 945: 'bell_pepper',
 946: 'cardoon',
 947: 'mushroom',
 948: 'Granny_Smith',
 949: 'strawberry',
 950: 'orange',
 951: 'lemon',
 952: 'fig',
 953: 'pineapple',
 954: 'banana',
 955: 'jackfruit',
 956: 'custard_apple',
 957: 'pomegranate',
 958: 'hay',
 959: 'carbonara',
 960: 'chocolate_sauce',
 961: 'dough',
 962: 'meat_loaf',
 963: 'pizza',
 964: 'potpie',
 965: 'burrito',
 966: 'red_wine',
 967: 'espresso',
 968: 'cup',
 969: 'eggnog',
 970: 'alp',
 971: 'bubble',
 972: 'cliff',
 973: 'coral_reef',
 974: 'geyser',
 975: 'lakeside',
 976: 'promontory',
 977: 'sandbar',
 978: 'seashore',
 979: 'valley',
 980: 'volcano',
 981: 'ballplayer',
 982: 'groom',
 983: 'scuba_diver',
 984: 'rapeseed',
 985: 'daisy',
 986: "yellow_lady's_slipper",
 987: 'corn',
 988: 'acorn',
 989: 'hip',
 990: 'buckeye',
 991: 'coral_fungus',
 992: 'agaric',
 993: 'gyromitra',
 994: 'stinkhorn',
 995: 'earthstar',
 996: 'hen-of-the-woods',
 997: 'bolete',
 998: 'ear',
 999: 'toilet_tissue'}